AWSTemplateFormatVersion: 2010-09-09

Description: MadeInJLM 2020 Cloud Computing series

Parameters:
  WebsiteDomainName:
    Type: String
    Description: Website Domain Name
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  WebsiteBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteDomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'

  IamInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  IamInstanceProfile: 
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: "/"
      Roles: 
        - !Ref IamInstanceRole 

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref IamInstanceProfile
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          amazon-linux-extras install python3.8
          pip3.8 install Flask
          cd /root/
          cat << EOF > server.py
          from socket import gethostname
          from flask import Flask, request

          app = Flask(__name__)
          
          @app.route('/ip-address')
          def ip_address():
              return f"Hello to {request.remote_addr} from hostname {gethostname()}"

          EOF
          export FLASK_APP=server.py
          python3.8 -m flask run --host 0.0.0.0 --port 80 &

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: My EC2 Instance Security Group
      GroupName: MyEc2Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
Outputs:
  WebsiteURL:
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Description: URL for website hosted on S3
  EC2InstanceId:
    Value: !Ref EC2Instance
    Description: The ID of the EC2 Instance
  EC2InstanceDns:
    Value: !GetAtt EC2Instance.PublicDnsName
    Description: The DNS of the EC2 Instance
